# Change these first
owner: Open-Attestation # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: OpenAttestation 
    url: https://www.openattestation.com


status-website:
  baseUrl: /statuspage

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
